config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  root to: 'top_pages#index'

  get '/home', to: 'top_pages#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :users, except: [:index, :show] do
    member do
      get :my_reservation
      get :my_reserved_shop
    end
  end

  resources :shops do
    member do
      get :canceled
      get :entered
      delete :reset
    end
    collection do
      get :my_shop
    end
    resources :reservations, only: [:show, :new, :create, :update, :destroy] do
      member do
        patch :cancel
        patch :enter
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :wait_time, presence: true

  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :already_relationships, dependent: :destroy
  has_many :reserved_users, through: :already_relationships, source: :user

  def self.ransackable_attributes(auth_object = nil)
    %w[name place created_at]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def set_expected
    DateTime.now + Rational(wait_time, 24 * 60)
  end

  def total_people_number
    n = 0
    reservations.yet.each do |reservation|
      n += reservation.people_number
    end
    n
  end

  def delete_all_reservation
    reservations.destroy_all
  end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy, :reset]
  before_action :set_shop, only: [:edit, :update, :destroy, :reset]
  before_action :shop_owner_or_redirect, only: [:show, :entered, :canceled]

  def index
    @q = Shop.where.not(user_id: current_user.id).ransack(params[:q])
    @shops = @q.result(distinct: true).page(params[:page]).per(12)
  end

  def my_shop
    @q = Shop.where(user_id: current_user.id).ransack(params[:q])
    @shops = @q.result(distinct: true).page(params[:page]).per(12)
  end

  def show
  end

  def entered
  end

  def canceled
  end

  def new
    @shop = Shop.new
    @reservation = Reservation.new
  end

  def create
    @shop = current_user.shops.new(shop_params)
    if @shop.save
      redirect_to shop_url(@shop), notice: "#{@shop.name}を登録しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to shop_url(@shop), notice: "#{@shop.name}を更新しました"
    else
      render :new
    end
  end

  def destroy
    @shop.destroy
    redirect_to my_shop_shops_url, notice: "#{@shop.name}を削除しました"
  end

  def reset
    @shop.delete_all_reservation
    redirect_to shop_url(@shop), notice: "#{@shop.name}の予約状況をリセットしました"
  end

  private

  def correct_user
    unless current_user.shops.find_by(id: params[:id])
      redirect_to root_url
    end
  end

  def set_shop
    @shop = current_user.shops.find(params[:id])
  end

  def shop_owner_or_redirect
    @shop = Shop.find(params[:id])
    unless current_user.shops.find_by(id: params[:id])
      redirect_to new_shop_reservation_path(@shop)
    else
      @reservations = @shop.reservations.order('reserve_on desc')
    end
  end

  def shop_params
    params.require(:shop).permit(:name, :place, :image, :wait_time)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.slim
- if shop.errors.present?
  .alert.alert-warning
    ul#error_explanation
      - shop.errors.full_messages.each do |message|
        li = message

= form_with model: shop, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'shop_name'
  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control', id: 'shop_place'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control', id: 'shop_image'
  .form-group
    = f.label :wait_time
    br
    = f.select :wait_time, [["0",0],["10",10],["20",20],["30",30],["40",40],["50",50],["60",60],["70",70],["80",80],["90",90],["100",100],["110",110],["120",120]],{} ,class: 'form-control custom-select', id: 'shop_wait_time'
  .text-center = f.submit nil, class: 'btn btn-primary mr-3'

app/views/shops/_link.html.slim
= link_to '詳細情報の編集', edit_shop_path(shop), class: 'btn btn-success mr-3'
= link_to 'お店の削除', shop, method: :delete, data: { confirm: "#{shop.name}を削除します。よろしいですか。" }, class: 'btn btn-danger mr-3'

app/views/shops/_management.html.slim
.row
  .col-lg-12
    h3.inline-left.text-muted = shop.name
  .col-lg-6.col-md-8.col-sm-12.inline-left
    - if shop.image.attached?
      = image_tag shop.image, class:"management-img"
    - else
      = image_tag 'noimage.png', class:"management-img"
  br
  
  .col-lg-6
    h3
      = shop.reservations.yet.count
      | 組
      = shop.total_people_number
      | 人待ち
    h5
      strong
        h5 設定予約時間
        .btn.btn-secondary = shop.set_expected.to_s(:ja)

    table.table
      tbody
        tr
          td= shop.place

    = form_with model: shop, local: true do |f|
      .form-inline
        .field
          = f.label :wait_time
        .field
          = f.select :wait_time, [["0",0],["10",10],["20",20],["30",30],["40",40],["50",50],["60",60],["70",70],["80",80],["90",90],["100",100],["110",110],["120",120]],{} ,class: 'form-control custom-select', id: 'shop_wait_time'
        .action
          = f.submit nil, class: 'btn btn-primary'
    br

  .col-lg-12
    .inline-right = link_to 'リセット', reset_shop_path(shop), method: :delete, data: { confirm: "#{shop.name}の予約状況をリセットします。よろしいですか？" }, class: 'btn btn-danger mr-3'
    ul.nav.nav-tabs
      li.nav-item
        = link_to shop_path(shop), class: "nav-link #{'active' if current_page?(shop_path(shop))}" do
          | 未入店
          span.badge.badge-primary
            = shop.reservations.yet.count
      li.nav-item
        = link_to entered_shop_path(shop), class: "nav-link #{'active' if current_page?(entered_shop_path(shop))}" do
          | 入店済み
          span.badge.badge-dark
            = shop.reservations.enter.count
      li.nav-item
        = link_to canceled_shop_path(shop), class: "nav-link #{'active' if current_page?(canceled_shop_path(shop))}" do
          | キャンセル
          span.badge.badge-danger
            = shop.reservations.cancel.count

app/views/shops/_search.html.slim
= search_form_for q, class: 'mb-5' do |f|
  .form-group.row
    .col-lg-1.offset-lg-2
      strong = f.label :name_cont, '店名', class: 'col-form-label'
    .col-lg-6
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    .col-lg-1.offset-lg-2
      strong = f.label :place_cont, '場所', class: 'col-form-label'
    .col-lg-6
      = f.search_field :place_cont, class: 'form-control'
  .text-center
      = f.submit class: 'btn btn-outline-primary'

.btn.btn-outline-primary = sort_link(q, :created_at, default_order: :desc)

br


app/views/shops/canceled.html.slim
= render partial: 'management', locals: { shop: @shop }
    
table.table.table-hover
  thead.thead-default
    tr
      th= Reservation.human_attribute_name(:reserve_on)
      th= User.human_attribute_name(:name)
      th= Reservation.human_attribute_name(:people_number)
    tbody
      - @reservations.cancel.each do |reservation|
        tr
          td= reservation.reserve_on.to_s(:ja)
          td= reservation.user.name
          td= reservation.people_number

= render partial: 'link', locals: { shop: @shop }

app/views/shops/edit.html.slim
.row
  .col-lg-12
    h2.text-center.text-muted お店の編集

= render partial: 'form', locals: { shop: @shop }

app/views/shops/entered.html.slim
= render partial: 'management', locals: { shop: @shop }

table.table.table-hover
  thead.thead-default
    tr
      th= Reservation.human_attribute_name(:reserve_on)
      th= User.human_attribute_name(:name)
      th= Reservation.human_attribute_name(:people_number)
      th
    tbody
      - @reservations.enter.each do |reservation|
        tr
          td= reservation.reserve_on.to_s(:ja)
          td= reservation.user.name
          td= reservation.people_number
          td
            - if reservation.yet?
              = link_to '入店', enter_shop_reservation_path(@shop, reservation), method: :patch, class: 'btn btn-primary mr-3'

= render partial: 'link', locals: { shop: @shop }

app/views/shops/index.html.slim
.row
  .col-lg-12
    h3.text-center.text-muted 予約できるお店一覧
  .col-lg-12
    = render partial: 'search', locals: { q: @q }
  .col-lg-12.
    = render partial: 'layouts/display', locals: { shops: @shops }

app/views/shops/my_index.html.slim
.row
  .col-lg-12
    h2.inline-left 自分のお店一覧
    .inline-right = link_to 'お店の追加', new_shop_path, class: 'btn btn-primary'
  .col-lg-12
    = render partial: 'search', locals: { q: @q }
  .col-lg-12
    = render partial: 'display', locals: { shops: @shops }

app/views/shops/my_shop.html.slim
.row
  .col-lg-12
    h3.text-center.text-muted 自分のお店一覧
    .inline-right = link_to 'お店の追加', new_shop_path, class: 'btn btn-primary'
  .col-lg-12
    = search_form_for @q, url: my_shop_shops_path, class: 'mb-5' do |f|
      .form-group.row
        .col-lg-1.offset-lg-2
          strong = f.label :name_cont, '店名', class: 'col-form-label'
        .col-lg-6
          = f.search_field :name_cont, class: 'form-control'
      .form-group.row
        .col-lg-1.offset-lg-2
          strong = f.label :place_cont, '場所', class: 'col-form-label'
        .col-lg-6
          = f.search_field :place_cont, class: 'form-control'
      .text-center
          = f.submit class: 'btn btn-outline-primary'
    .btn.btn-outline-primary = sort_link(@q, :created_at)
    = render partial: 'layouts/display', locals: { shops: @shops }

app/views/shops/new.html.slim
.row
  .col-lg-12
    h2.text-center.text-muted お店の追加

= render partial: 'form', locals: { shop: @shop }

app/views/shops/show.html.slim
= render partial: 'management', locals: { shop: @shop }
    
table.table
  thead.thead-default
    tr
      th= Reservation.human_attribute_name(:reserve_on)
      th= User.human_attribute_name(:name)
      th= Reservation.human_attribute_name(:people_number)
      th
      th
    tbody
      - @reservations.yet.each do |reservation|
        tr class="#{reservation.divide_time if reservation.divide_time}"
          td= reservation.reserve_on.to_s(:ja)
          td= reservation.user.name
          td= reservation.people_number
          td
            - if reservation.yet?
              = link_to '入店', enter_shop_reservation_path(@shop, reservation), method: :patch, class: 'btn btn-primary mr-3'
          td
            - if reservation.yet?
              button.btn.btn-outline-secondary[type="button" data-toggle="modal" data-target="#change-time#{reservation.id}"]
                  | 時間変更

- @reservations.yet.each do |reservation|
  .modal.fade[id="change-time#{reservation.id}"tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true"]
    .modal-dialog.modal-lg[role="document"]
      .modal-content
        .modal-header.modal-change-time
          h5.modal-title 予約時間の変更
          button.close[type="button" data-dismiss="modal" aria-label="Close"]
            span[aria-hidden="true"]
              | &times;
        .modal-body.modal-change-time
          = form_with model: reservation, url: [reservation.shop, reservation], local: true do |f|
            .form-inline
              .form-group
                = f.datetime_select :reserve_on, {}, class: 'form-control custom-select inline-ajust' 
              .form-group
                = f.submit '変更する',class: 'btn btn-outline-light btn-change-time'
            br
            p 時間を変更すると、予約者にメールで通知されます
        .modal-footer.modal-change-time
          button.btn.btn-outline-light[type="button" data-dismiss="modal"]
            | Close

= render partial: 'link', locals: { shop: @shop }