config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  root to: 'top_pages#index'

  get '/home', to: 'top_pages#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :users, except: [:index, :show] do
    member do
      get :my_reservation
      get :my_reserved_shop
    end
  end

  resources :shops do
    member do
      get :canceled
      get :entered
      delete :reset
    end
    collection do
      get :my_shop
    end
    resources :reservations, only: [:show, :new, :create, :update, :destroy] do
      member do
        patch :cancel
        patch :enter
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase, unless: :uid?

  has_secure_password validations: false

  validates :name, presence: true, unless: :uid?
  validates :email, presence: true, unless: :uid?, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  has_many :messages, dependent: :destroy
  has_many :shops, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :already_relationships, dependent: :destroy
  has_many :reserved_shops, through: :already_relationships, source: :shop

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    email = auth[:info][:email]
    image = auth[:info][:image]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.email = email
      user.image_url = image
    end
  end

  def add_reserved_shop(shop)
    self.already_relationships.find_or_create_by(shop_id: shop.id)
  end

  def reserved?(shop)
    self.reserved_shops.include?(shop)
  end

  private

  def email_downcase
    self.email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy, :my_reservation]
  before_action :set_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def edit
    if current_user.email == 'test@gmail.com'
      redirect_to root_url
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to root_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}を削除しました。」"
  end

  def my_reservation
    @reservations = current_user.reservations.yet
  end

  def my_reserved_shop
    @shops = current_user.reserved_shops.page(params[:page]).per(4)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    unless current_user == User.find(params[:id])
      redirect_to root_url
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
- if user.errors.present?
  .alert.alert-warning
    ul#error_explanation
      - user.errors.full_messages.each do |message|
        li = message

= form_with model: user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード（確認）'
    = f.password_field :password_confirmation, class: 'form-control'
  .text-center = f.submit '登録する',class: 'btn btn-primary'

app/views/users/edit.html.slim
.row
  .col-lg-12
    h3.text-center.text-muted
      = @user.name
      | さんの詳細情報

- if @user.errors.present?
  .alert.alert-warning
    ul#error_explanation
      - @user.errors.full_messages.each do |message|
        li = message

= form_with model: @user, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  p
    button[type="button" class="btn btn-outline-secondary" data-toggle="collapse" data-target="#password-form" aria-expanded="false" aria-controls="collapseExample"]
      span.fa.fa-chevron-down パスワードの変更
  .collapse#password-form
    .card.card-body
      .form-group
        = f.label :password, '新しいパスワード'
        = f.password_field :password, class: 'form-control'
      .form-group
        = f.label :password_confirmation, '新しいパスワード（確認）'
        = f.password_field :password_confirmation, class: 'form-control'
  .text-center = f.submit '登録する',class: 'btn btn-primary'

app/views/users/my_reservation.html.slim
.row
  .col-lg-12
    table.table.table-hover
      thead.thead-default
        tr
          th= Reservation.human_attribute_name(:reserve_on)
          th= Shop.human_attribute_name(:name)
          th= Reservation.human_attribute_name(:people_number)
        tbody
          - @reservations.each do |reservation|
            tr
              td
                = link_to shop_reservation_path(reservation.shop, reservation), class: 'btn btn-secondary'
                  .reservation_link = reservation.reserve_on.to_s(:ja)
              td= reservation.shop.name
              td= reservation.people_number

app/views/users/my_reserved_shop.html.slim
h3.text-center.text-muted 予約したことのあるお店

= render partial: 'layouts/display', locals: { shops: @shops }

app/views/users/new.html.slim
.row
  .col-lg-12
    h3.text-center.text-muted ユーザー登録

= render partial: 'form', locals: { user: @user }