config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  root to: 'top_pages#index'

  get '/home', to: 'top_pages#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :users, except: [:index, :show] do
    member do
      get :my_reservation
      get :my_reserved_shop
    end
  end

  resources :shops do
    member do
      get :canceled
      get :entered
      delete :reset
    end
    collection do
      get :my_shop
    end
    resources :reservations, only: [:show, :new, :create, :update, :destroy] do
      member do
        patch :cancel
        patch :enter
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :reserve_on, presence: true
  validates :people_number, presence: true

  enum status: { yet: 0, enter: 1, cancel: 2 }

  belongs_to :user
  belongs_to :shop

  def reserve(shop)
    self.shop_id = shop.id
    self.reserve_on = shop.set_expected
  end

  def divide_time
    diff_time = ( reserve_on - DateTime.now ) / 60
    if diff_time < 0
      "red"
    elsif diff_time < 10
      "blue"
    else
      "normal"
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :different_user, only: [:new, :show]
  before_action :correct_owner, only: [:update, :enter]
  before_action :set_shop, only: [:new, :show, :create]
  before_action :set_reservation, only: [:update, :enter]

  def index
    @reservations = current_user.reservations.yet
  end

  def new
    reservation = current_user.reservations.yet.find_by(shop_id: params[:shop_id])
    #未予約か予約をキャンセルした場合のみ、予約できるようにする
    if reservation
      redirect_to shop_reservation_path(@shop, reservation)
    end
    @reservation = Reservation.new
  end

  def show
    @reservation = current_user.reservations.find(params[:id])
  end

  def create
    reservation = current_user.reservations.new(reservation_params)
    reservation.reserve(@shop)
    reservation.save!

    unless current_user.reserved?(@shop)
      current_user.add_reserved_shop(@shop)
    end

    message = reservation.shop.user.messages.build
    message.reserve(reservation)
    message.save!

    redirect_to root_url, notice: "#{@shop.name}の予約を#{reservation.reserve_on.to_s(:ja)}で予約をお取りしました"
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update!(change_time_params)

    message = @reservation.user.messages.build
    message.change_reservation_time(@reservation)
    message.save!

    ReservationMailer.inform_change_time(@reservation, @reservation.user).deliver

    redirect_to shop_path(@reservation.shop), notice: "#{@reservation.user.name}さんの予約時間を#{@reservation.reserve_on.to_s(:ja)}に変更しました"
  end

  def cancel
    unless reservation = current_user.reservations.find(params[:id])
      redirect_to root_url
    end
    reservation.cancel!

    message = reservation.shop.user.messages.build
    message.cancel(reservation)
    message.save!

    redirect_to root_url, notice: "#{reservation.shop.name}の予約をキャンセルしました"
  end

  def enter
    @reservation = Reservation.find(params[:id])
    @reservation.enter!
    redirect_to shop_path(@reservation.shop), notice: "#{@reservation.user.name}が入店しました"
  end

  private

  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def different_user
    if current_user.shops.find_by(id: params[:shop_id])
      redirect_to root_url
    end
  end

  def correct_owner
    unless current_user == Reservation.find(params[:id]).shop.user
      redirect_to root_url
    end
  end

  def reservation_params
    params.require(:reservation).permit(:people_number)
  end

  def change_time_params
    params.require(:reservation).permit(:reserve_on)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_wait_number.html.slim
javascript:
  function initMap(){
    geocoder = new google.maps.Geocoder();
    
    var address = "#{@shop.place}";

    geocoder.geocode({'address': address}, function(results, status) {
      if (status === google.maps.GeocoderStatus.OK) {
        let map = new google.maps.Map(document.getElementById('map'),{
        center: results[0].geometry.location,
        zoom: 15
        });
        var marker = new google.maps.Marker({ map: map, position: results[0].geometry.location });
      }
    });
  }

script[src="https://maps.googleapis.com/maps/api/js?key=#{ENV['MAP_API_KEY']}&callback=initMap" async defer]

.row
  .col-lg-6.col-xs-12
    h3.text-muted = shop.name
    - if shop.image.attached?
      = image_tag shop.image, class:"management-img"
    - else
      = image_tag 'noimage.png', class:"management-img"
  - if shop.place.present?
    .col-lg-5.col-xs-12.inline-right
      #map
      .text-center
        h5 = shop.place

app/views/reservations/new.html.slim
= render partial: 'wait_number', locals: { shop: @shop }

.col-lg-6.col-xs-12
  - if @shop.wait_time == 0
    h4
      | 現在待ち時間は
      strong ０分
      | です。
    h4 ご来店いただければ、ご入店できます。
  - else
    h2 
      = @shop.reservations.yet.count
      | 組
      = @shop.total_people_number
      | 人待ち
    h5 
      | 現在予約できる時間
      br
      .btn.btn-lg.btn-secondary = @shop.set_expected.to_s(:ja)
      
    = form_with model: @reservation, url: [@shop, @reservation], local: true do |f|
      .form-group
        = f.select :people_number, [["1",1],["2",2],["3",3],["4",4],["5",5],["6",6],["7",7],["8",8]],{} ,class: 'form-control custom-select', id: 'shop_wait_time'
        | 人
      = f.submit '予約する', data: { confirm: "#{@shop.set_expected.to_s(:ja)}で予約をお取りします。よろしいですか?"}, class: 'btn btn-primary'

app/views/reservations/show.html.slim
= render partial: 'wait_number', locals: { shop: @shop }

br

.col-lg-12
  h4
    | 現在の予約時間
    br
    .btn.btn-lg.btn-secondary = @reservation.reserve_on.to_s(:ja)
  br
  = link_to '予約のキャンセル', cancel_shop_reservation_path(@shop, @reservation), method: :patch, data: { confirm: "#{@shop.name}の予約をキャンセルします。よろしいですか。" }, class: 'btn btn-danger mr-3'