config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'
  root to: 'top_pages#index'

  get '/home', to: 'top_pages#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create'

  resources :users, except: [:index, :show] do
    member do
      get :my_reservation
      get :my_reserved_shop
    end
  end

  resources :shops do
    member do
      get :canceled
      get :entered
      delete :reset
    end
    collection do
      get :my_shop
    end
    resources :reservations, only: [:show, :new, :create, :update, :destroy] do
      member do
        patch :cancel
        patch :enter
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :messages, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_display.html.slim
.row
  - shops.each do |shop|
    .col-lg-3.col-md-4.col-sm-6
      .card
        = link_to shop_path(shop)
          - if shop.image.attached?
            = image_tag shop.image, class:"card-img-top"
          - else
            = image_tag 'noimage.png', class:"card-img-top"
        .card-body
          h6
            strong = shop.name.truncate(12)
          h6.text-muted.inline-left = shop.place.truncate(10)
          h6.inline-right
            = shop.wait_time
            | 分
  .col-lg-12
    = paginate shops
  

app/views/layouts/_flash_yield.html.slim
- if flash.notice.present?
  .alert.alert-success= flash.notice
= yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Noline
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .wrapper
      nav.navbar.navbar-expand-lg.fixed-top.custom-hamburger
          = link_to 'Noline', root_path, class: 'navbar-brand nav-link navi-logo'
          button[class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbar-menu"] 
            span.navbar-toggler-icon

          .collapse.navbar-collapse#navbar-menu
            ul.navbar-nav.mr-auto
              li.nav-item
                button.btn.btn-outline-secondary[type="button" data-toggle="modal" data-target="#how-to"]
                  | 使い方
            ul.navbar-nav.ml-auto
              - if current_user
                li.nav-item= link_to '予約する', shops_path, class: 'nav-link' 
                li.nav-item= link_to '自分の予約', my_reservation_user_path(current_user), class: 'nav-link' 
                li.nav-item= link_to '予約したことあるお店', my_reserved_shop_user_path(current_user), class: 'nav-link' 
                li.nav-item= link_to messages_index_path, class: 'nav-link' 
                  span.fa.fa-bell-o
                  span 通知 
                  span.badge.badge-dark
                    = current_user.messages_yet_count
                li.nav-item= link_to my_shop_shops_path, class: 'nav-link' 
                  span.fa.fa-home
                  span 自分のお店     
                li.nav-item
                  div.dropdown
                    button.btn.btn-outline-secondary.dropdown-toggle[type="button"
                      data-toggle="dropdown"
                      aria-haspopup="true"
                      aria-expanded="false"]
                      = current_user.name
                    div.dropdown.show
                      div.dropdown-menu
                        - unless current_user.email=='test@gmail.com'
                          = link_to 'ユーザー設定', edit_user_path(current_user), class: 'dropdown-item'
                          div.dropdown-divider
                        = link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item'
              - else
                li.nav-item= link_to '新規登録', new_user_path, class: 'nav-link'     
                li.nav-item= link_to 'ログイン', login_path, class: 'nav-link' 
                
      - unless controller.controller_name == 'top_pages' && controller.action_name == 'index'
        .container
          = render partial: 'layouts/flash_yield'
      - else
          = yield

    #how-to.modal.fade[tabindex="-1" role="dialog" aria-labelledby="label1" aria-hidden="true"]
      .modal-dialog.modal-lg[role="document"]
        .modal-content
          .modal-body.modal-how-to
            button.close[type="button" data-dismiss="modal" aria-label="Close"]
              span[aria-hidden="true"]
                | &times;
            h5 予約するとき
            ol
              li ナビバーから「予約する」を選択します
              li 予約したいお店を選びます
              li 表示されている時間でよければ、人数を選んで予約します
            h5 キャンセルするとき
            ol
              li ナビバーから「予約する」を選択します
              li キャンセルするお店を選びます
              li キャンセルします

            hr

            h5 お店の登録
            ol
              li ナビバーから「自分のお店一覧」を選択します
              li 「お店の追加」を選びます
              li お店を登録します
            h5 予約を管理する
            ol
              li ナビバーから「自分のお店一覧」を選択します
              li 予約を管理するお店を選びます
              li 予約管理画面
            .text-center = image_tag 'manage.png'
            .blue-description 予約時間まで10分を切った予約
            .red-description 予約時間を過ぎた予約
            .modal-footer
              button.btn.btn-outline-light[type="button" data-dismiss="modal"]
                | Close